blank_issues_enabled: true
contact_links:
  - name: Check out VapinGamers Rumble channel here!
    url: https://rumble.com/c/VapinGamers
  - name: Check out GlobalGamer2015 Rumble channel here!
    url: https://rumble.com/c/c-4699930
